---
- name: Déployer l'application Spring Boot
  hosts: web
  become: true

  tasks:
    - name: Installer Java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Copier les fichiers du projet
      copy:
        src: "{{ playbook_dir }}/"
        dest: /opt/springbootapp/
        owner: root
        group: root
        mode: '0755'

